Unit tests server controller
kuzzleio/sdk-csharp pull request #16
Opened 2019-06-21 09:34 UTC by ThomasF34

:warning: depends on #14 

## What does this PR do ?
Add unit test for server controller. 

### Other changes
Fix the query made in `getStatsAsync` function : action was `getLastStats` while [it should be](https://docs.kuzzle.io/core/1/api/controllers/server/get-stats/) `getStats`

2019-06-21 10:19 UTC, Aschen requested changes

2019-06-21 10:19 UTC, Aschen commented on Kuzzle.Tests/API/Controllers/ServerControllerTest.cs
> +        public async void GetiAllStatsTest(){
```suggestion
        public async void GetAllStatsTest(){
```

2019-06-21 11:52 UTC, scottinet requested changes
Also, _there really was a cake_.

2019-06-21 11:52 UTC, scottinet commented on Kuzzle.Tests/API/Controllers/ServerControllerTest.cs
> +        public async void InfoTest(){
You forgot to verify what the function returns.

2019-06-21 11:52 UTC, scottinet commented on Kuzzle.Tests/API/Controllers/ServerControllerTest.cs
> +        public async void ConfigTest(){
ditto

2019-06-24 09:33 UTC, alexandrebouthinon commented
@ThomasF34 : You should now be able to rebase this branch on 0-dev

2019-06-24 10:58 UTC, Aschen approved these changes

2019-06-24 11:20 UTC, benoitvidis approved these changes

2019-06-25 08:08 UTC, scottinet approved these changes

2019-06-25 08:09 UTC, merged