Add unit test for Realtime Controller
kuzzleio/sdk-csharp pull request #18
Opened 2019-06-24 09:46 UTC by ThomasF34

## What does this PR do ?
Add unit test for realtime controller. 

### Other changes
- Fix error on Count function : It should return the `count` attribute of the result
- Fix mocking error : The `IKuzzleAPI` interface contains objects (like `NetworkProtocol`) that should be mocked. To mock recursively, i added the option in the creation of the mock.

2019-06-24 09:47 UTC, ThomasF34 commented
Feel free to tell me if you see more tests that could be done

2019-06-25 08:34 UTC, scottinet requested changes

2019-06-25 08:34 UTC, scottinet commented on Kuzzle.Tests/API/Controllers/RealtimeControllerTest.cs
> +            MemberData(nameof(MockGenerators.GenerateSubscribeOptions),
(nitpicking) My view on this is that generators only used by one class should be made local to that class' test file. The global `MockGenerators` class should only contain generators that will be used by multiple classes, such as search options or filters (will be used in the future by the security controller).

2019-06-25 08:34 UTC, scottinet commented on Kuzzle.Tests/API/Controllers/RealtimeControllerTest.cs
> +            //Then we can test if unsubcription is working
Not really: you only check that the method sends the correct request, but you do not check that we correctly dereferenced the subscription.

You can do that by either sending a notification to that channel and verify that the mocked `NotificationHandler` is not invoked, and/or by checking directly the content of the rooms cache maintained by the controller object.

2019-06-26 12:09 UTC, scottinet approved these changes

2019-06-26 12:09 UTC, scottinet commented on Kuzzle.Tests/API/Controllers/RealtimeControllerTest.cs
> +            Mock<RealtimeController.NotificationHandler> mockNotifHand = new Mock<RealtimeController.NotificationHandler>();
(nitpicking) I'm not fond of truncated variable names, to me `notificationHandlerMock` is far more explicit and easier to read.

2019-06-27 12:51 UTC, merged