Add documentation runner
kuzzleio/sdk-csharp pull request #20
Opened 2019-06-28 13:21 UTC by Aschen

## What does this PR do ?

Bootstrap the documentation and add a runner to execute the snippets with the test framework.

### How should this be manually tested?

  - Step 1 : Run the following command `docker-compose -f .ci/doc/docker-compose.yml run doc-tests node index`

### Other changes

### Boyscout

2019-07-01 13:51 UTC, scottinet requested changes
typo

2019-07-01 13:51 UTC, scottinet commented on doc/0/example/example/snippets/example.cs
> +  Console.WriteLine("Does not exists");
```suggestion
  Console.WriteLine("Does not exist");
```

2019-07-01 13:51 UTC, scottinet commented on doc/0/example/example/snippets/example.test.yml
> +expected: Does not exists
```suggestion
expected: Does not exist
```

2019-07-01 14:59 UTC, xbill82 approved these changes

2019-07-02 07:19 UTC, scottinet approved these changes

2019-07-02 07:19 UTC, merged