Add Auth Controller documentation
kuzzleio/sdk-csharp pull request #29
Opened 2019-07-29 15:31 UTC by Shiranuit

## What does this PR do ?

Add Auth controller documentation and tests

### How should this be manually tested?
Run: `$ docker-compose -f .ci/doc/docker-compose.yml run doc-tests node index`

2019-07-30 13:10 UTC, y-abs approved these changes

2019-07-30 13:10 UTC, y-abs commented on doc/1/controllers/auth/delete-my-credentials/index.md
> +Delete the current user's credentials for the specified strategy. If the credentials that generated the current JWT are removed, the user will remain logged in until he logs out or his session expire
```suggestion
Delete the current user's credentials for the specified strategy. If the credentials that generated the current JWT are removed, the user will remain logged in until he logs out or his session expires. After that they will no longer be able to log in with the deleted credentials.
```

2019-07-30 13:10 UTC, Yoann-Abbes commented on doc/1/controllers/auth/refresh-token/index.md
> +A JObject which has the following properties:
```suggestion
A JObject with the following properties:
```

2019-07-30 16:49 UTC, Aschen commented
There is no need to put 2 labels, only one will be used to construct the changelog.
You can just use `changelog:documentation`

2019-08-01 15:45 UTC, Aschen requested changes

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/check-token/index.md
> +| valid      | <pre>bool</pre>   | Token validity                   |
Property name should be between backtick (this comment apply everywhere)

```suggestion
|  `valid`      | <pre>bool</pre>   | Token validity                   |
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/check-token/snippets/check-token.cs
> +  JObject response = (await kuzzle.Auth.LoginAsync("local", JObject.Parse("{username: 'foo', password: 'bar'}")));
Why parenthesis around the call ?
Also you should wrap line greater than 80 column (apply everywhere)

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/check-token/snippets/check-token.test.yml
> +name: auth#checkToken
```suggestion
name: Auth#checkTokenAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/create-my-credentials/snippets/create-my-credentials.test.yml
> +name: auth#CreateMyCredentials
```suggestion
name: Auth#CreateMyCredentialsAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/credentials-exist/snippets/credentials-exist.test.yml
> +name: auth#credentialsExist
```suggestion
name: Auth#CredentialsExistAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/delete-my-credentials/snippets/delete-my-credentials.test.yml
> +name: auth#deleteMyCredentials
```suggestion
name: Auth#DeleteMyCredentialsAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/get-current-user/snippets/get-current-user.test.yml
> +name: auth#getCurrentUser
```suggestion
name: Auth#getCurrentUserAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/get-my-credentials/snippets/get-my-credentials.test.yml
> +name: auth#getMyCredentials
```suggestion
name: Auth#getMyCredentialsAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/get-my-rights/snippets/get-my-rights.test.yml
> +name: auth#getMyRights
```suggestion
name: Auth#GetMyRightsAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/get-strategies/snippets/get-strategies.test.yml
> +name: auth#getStrategies
```suggestion
name: Auth#GetStrategiesAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/login/snippets/login.test.yml
> +name: auth#login
```suggestion
name: Auth#LoginAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/logout/snippets/logout.test.yml
> +name: auth#logout
```suggestion
name: Auth#LogoutAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/refresh-token/snippets/refresh-token.test.yml
> +name: auth#refreshToken
```suggestion
name: Auth#RefreshTokenAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/update-my-credentials/snippets/update-my-credentials.test.yml
> +name: auth#updateMyCredentials
```suggestion
name: Auth#UpdateMyCredentialsAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/update-self/snippets/update-self.test.yml
> +name: auth#updateSelf
```suggestion
name: Auth#UpdateSelfAsync
```

2019-08-01 15:45 UTC, Aschen commented on doc/1/controllers/auth/validate-my-credentials/snippets/validate-my-credentials.test.yml
> +name: auth#validateMyCredentials
```suggestion
name: Auth#ValidateMyCredentialsAsync
```

2019-08-02 14:29 UTC, Aschen approved these changes

2019-08-02 14:29 UTC, merged