Add Realtime Controller Documentation
kuzzleio/sdk-csharp pull request #30
Opened 2019-07-30 08:37 UTC by Shiranuit

## What does this PR do ?

Add Realtime controller documentation and tests

### How should this be manually tested?
Run: `$ docker-compose -f .ci/doc/docker-compose.yml run doc-tests node index`

2019-07-30 14:49 UTC, y-abs requested changes

2019-07-30 14:49 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/publish/index.md
> +Sends a real-time message to Kuzzle. The message will be dispatched to all clients with subscriptions matching the index, the collection and the message content.
```suggestion
Sends a real-time message to Kuzzle. The message will be broadcasted to all clients with subscriptions matching the index, the collection and the message content.
```

2019-07-30 14:49 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/publish/index.md
> +The index and collection are indicative and serve only to distinguish the rooms. They are not required to exist in the database
```suggestion
The index and collection are indicative and serve only to distinguish the rooms. They are not required to exist in the database.
```

2019-07-30 14:49 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/index.md
> +Listener function that will be called each time a new notifications is received.
```suggestion
Listener function that will be called each time a new notification is received.
```

2019-07-30 16:49 UTC, Aschen commented
There is no need to put 2 labels, only one will be used to construct the changelog.
You can just use `changelog:documentation`

2019-08-02 14:31 UTC, scottinet requested changes

2019-08-02 14:31 UTC, scottinet commented on doc/1/controllers/realtime/count/index.md
> +Count the number of subscribers for a subscription room
```suggestion
Counts the number of subscribers for a subscription room
```

Alternatively, I prefer [the raw API version](https://docs.kuzzle.io/core/1/api/controllers/realtime/count/) of this description:

```
Returns the number of other connections sharing the same subscription.
```

2019-08-02 14:31 UTC, scottinet commented on doc/1/controllers/realtime/count/snippets/count.cs
> +  Console.WriteLine("Currently " + count + " active subscription");
Use string litterals:

```suggestion
  Console.WriteLine($"Currently {count} active subscription");
```

2019-08-02 14:31 UTC, scottinet commented on doc/1/controllers/realtime/subscribe/index.md
> +public async Task<string> SubscribeAsync(
As per our newest wrapping rules, this should be written like this:

```csharp
public async Task<string> SubscribeAsync(
      string index, 
      string collection, 
      JObject filters,
      NotificationHandler 
      handler, 
      SubscribeOptions options = null);
```

2019-08-02 14:31 UTC, scottinet commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.cs
> +  Console.WriteLine("Document moved " + notification.Scope.ToString() + " from the scope");
Use string litterals.
Also, if the scope value is `in`, then the output will be in engrish.

2019-08-02 14:31 UTC, scottinet commented on doc/1/controllers/realtime/count/snippets/count.cs
> +  Console.WriteLine("Currently " + count + " active subscription");
This change should be applied to all code snippets.

2019-08-02 14:31 UTC, scottinet commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications.cs
> +    Console.WriteLine("Document " + id + " enter the scope");
```suggestion
    Console.WriteLine($"Document {id} entered the scope");
```

2019-08-02 14:31 UTC, scottinet commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications.cs
> +    Console.WriteLine("Document " + id + " leave the scope");
```suggestion
    Console.WriteLine($"Document {id} left the scope");
```

2019-08-07 15:16 UTC, y-abs requested changes

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/bulk/mwrite-async/index.md
> +description: Create or replace multiple documents directly into the storage engine.
```suggestion
description: Creates or replace multiple documents directly into the storage engine.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/bulk/mwrite-async/snippets/mwrite-async.test.yml
>  description: Create or replace multiple documents directly into the storage engine.
```suggestion
description: Creates or replace multiple documents directly into the storage engine.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/bulk/write-async/index.md
> +description: Create or replace a document directly into the storage engine.
```suggestion
description: Creates or replace a document directly into the storage engine.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/bulk/write-async/snippets/write-async.test.yml
>  description: Create or replace a document directly into the storage engine.
```suggestion
description: Creates or replace a document directly into the storage engine.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/count/index.md
> +Counts the number of subscribers for a subscription room
```suggestion
Counts the number of subscribers for a subscription room.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/publish/index.md
> +description: Publish a real-time message.
```suggestion
description: Publishes a real-time message.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/publish/snippets/publish.test.yml
> +description: Publish a realtime message.
```suggestion
description: Publishes a realtime message.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/index.md
> +description: Subscribe to real-time notifications.
```suggestion
description: Subscribes to real-time notifications.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/index.md
> +| `scope`           | <pre>string</pre><br/>(`all`)   | Subscribe to document entering or leaving the scope<br/>Possible values: `all`, `in`, `out`, `none`                           |
```suggestion
| `scope`           | <pre>string</pre><br/>(`all`)   | Subscribes to document entering or leaving the scope<br/>Possible values: `all`, `in`, `out`, `none`                           |
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/index.md
> +| `users`           | <pre>string</pre><br/>(`none`)  | Subscribe to users entering or leaving the room<br/>Possible values: `all`, `in`, `out`, `none`                               |
```suggestion
| `users`           | <pre>string</pre><br/>(`none`)  | Subscribes to users entering or leaving the room<br/>Possible values: `all`, `in`, `out`, `none`                               |
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/index.md
> +| `subscribeToSelf` | <pre>bool</pre><br/>(`true`)    | Subscribe to notifications fired by our own queries                                                                           |
```suggestion
| `subscribeToSelf` | <pre>bool</pre><br/>(`true`)    | Subscribes to notifications fired by our own queries                                                                           |
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.cs
> +  // Update the document so he isn't in the scope anymore
```suggestion
  // Updates the document so it isn't in the scope anymore
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.cs
> +  // Creates a document who is in the scope
```suggestion
  // Creates a document which is in the scope
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.test.yml
> +description: Subscribe to documents leaving the scope.
```suggestion
description: Subscribes to documents leaving the scope.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications.cs
> +  // Subscribe to notifications for documents containing a 'name' property
```suggestion
  // Subscribes to notifications for documents containing a 'name' property
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications.cs
> +  // Create a document matching the provided filters
```suggestion
  // Creates a document matching the provided filters
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/message-notifications.test.yml
> +description: Subscribe to message notifications.
```suggestion
description: Subscribes to message notifications.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications.test.yml
> +description: Simple subscribe to document notifications.
```suggestion
description: Subscribes to document notifications.
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/user-notifications.cs
> +  // Subscription to notifications and notifications when user join or leave
```suggestion
  // Subscription to notifications when user join or leave
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/user-notifications.cs
> +  // Set some volatile data
```suggestion
  // Sets some volatile data
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/user-notifications.cs
> +  // Subscribe to the same room with the second client
```suggestion
  // Subscribes to the same room with the second client
```

2019-08-07 15:16 UTC, Yoann-Abbes commented on doc/1/controllers/realtime/subscribe/snippets/user-notifications.test.yml
> +description: Subscribe to users joining or leaving the room.
```suggestion
description: Subscribes to users joining or leaving the room.
```

2019-08-14 07:59 UTC, y-abs approved these changes

2019-08-20 12:24 UTC, scottinet requested changes

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/bulk/mwrite-async/index.md
> +description: Creates or replace multiple documents directly into the storage engine.
```suggestion
description: Creates or replaces multiple documents directly into the storage engine.
```

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/bulk/mwrite-async/snippets/mwrite-async.test.yml
> +description: Creates or replace multiple documents directly into the storage engine.
```suggestion
description: Creates or replaces multiple documents directly into the storage engine.
```

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/bulk/write-async/index.md
> +description: Creates or replace a document directly into the storage engine.
```suggestion
description: Creates or replaces a document directly into the storage engine.
```

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/bulk/write-async/snippets/write-async.test.yml
> +description: Creates or replace a document directly into the storage engine.
```suggestion
description: Creates or replaces a document directly into the storage engine.
```

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/realtime/count/snippets/count.cs
> +  Console.WriteLine($"Currently {count} active subscription");
```suggestion
  Console.WriteLine($"Currently {count} active subscriptions");
```

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.cs
> +  // Subscribes to notifications when document leaves the scope
```suggestion
  // Subscribes to notifications when documents leave the scope
```

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.cs
> +    Console.WriteLine($"Document moved {scope} from the scope");
```suggestion
    Console.WriteLine($"Document moved {scope} of the scope");
```

Also, you don't template litterals here:

```suggestion
    Console.WriteLine("Document left the scope");
```
(and "Document entered the scope" when scope is `in`)

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.cs
> +  options.Scope = "out";
Either:
```suggestion
  options.Scope = "all";
```

Or you have to update this whole example because there won't be any `in` notifications sent.

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/realtime/subscribe/snippets/document-notifications-leave-scope.cs
> +  // Updates the document so he isn't in the scope anymore
```suggestion
  // Updates the document to make it leave the scope
```

2019-08-20 12:24 UTC, scottinet commented on doc/1/controllers/realtime/subscribe/snippets/user-notifications.cs
> +  // Subscription to notifications when user join or leave
```suggestion
  // Subscription to notifications sent whenever a user joins or leaves
```

2019-08-28 08:29 UTC, benoitvidis approved these changes

2019-08-29 09:22 UTC, scottinet approved these changes

2019-08-30 14:02 UTC, merged