Kuzzle v2 compatibility
kuzzleio/sdk-csharp pull request #43
Opened 2019-11-22 05:08 UTC by Aschen

## What does this PR do ?

Ensure SDK compatibility with Kuzzle v2:
 - Use Kuzzle v2 images in Docker Compose
 - Update the NuGet version

2019-11-26 10:39 UTC, scottinet requested changes
Documentation wording

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/bulk/import-async/index.md
> +```json
Because there are comments:

```suggestion
```js
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/bulk/import-async/index.md
> +Each item of the `successes` array is an object containing the action name as key and the corresponding object contain the following properties:
```suggestion
Each item of the `successes` array is an object, with the action name as key, and an  object value the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/bulk/import-async/index.md
> +Each item of the `errors` array is an object containing the action name as key and the corresponding object contain the following properties:
```suggestion
Each item of the `errors` array is an object, with the action name as key, and an object value with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/bulk/import-async/index.md
> +Each `error` object contain the following properties:
```suggestion
Each `error` object contains the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/bulk/mwrite-async/index.md
> +Each created or replaced document is an object of the `successes` array with the following properties:
```suggestion
Successful document imports are returned in the `successes` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/bulk/mwrite-async/index.md
> +Each errored document is an object of the `errors` array with the following properties:
```suggestion
Failed document imports are returned in the `errors` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/bulk/mwrite-async/index.md
> +| `document`  | <pre>JObject</pre> | Document that cause the error                                       |
```suggestion
| `document`  | <pre>JObject</pre> | Failed document                                      |
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-create-or-replace/index.md
> +Returns a `JObject` containing 2 arrays: `successes` and `errors`
```suggestion
Returns a `JObject` object with 2 array properties: `successes` and `errors`
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-create-or-replace/index.md
> +Each created document is an object of the `successes` array with the following properties:
```suggestion
Successful document creations/replacements are returned in the `successes` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-create-or-replace/index.md
> +Each errored document is an object of the `errors` array with the following properties:
```suggestion
Failed document imports are returned in the `errors` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-create-or-replace/index.md
> +| `document`  | <pre>JObject</pre> | Document that cause the error                                       |
```suggestion
| `document`  | <pre>JObject</pre> | Failed document                                       |
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-create/index.md
> +Each created document is an object of the `successes` array with the following properties:
```suggestion
Successful document creations are returned in the `successes` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-create/index.md
> +Each errored document is an object of the `errors` array with the following properties:
```suggestion
Failed document imports are returned in the `errors` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-create/index.md
> +| `document`  | <pre>JObject</pre> | Document that cause the error                                       |
```suggestion
| `document`  | <pre>JObject</pre> | Failed document                                      |
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-delete/index.md
> +Each deletion error is an object of the `errors` array with the following properties:
```suggestion
Failed deletions are returned in the `errors` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-get/index.md
> +The `successes` array contain the list of retrieved documents.
```suggestion
The `successes` array contains the list of retrieved documents.
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-get/index.md
> +The `errors` array contain the IDs of not found documents.
```suggestion
The `errors` array contains the document IDs which couldn't be retrieved.
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-replace/index.md
> +Each replaced document is an object of the `successes` array with the following properties:
```suggestion
Successful document replacements are returned in the `successes` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-replace/index.md
> +Each errored document is an object of the `errors` array with the following properties:
```suggestion
Failed replacements are returned in the `errors` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-replace/index.md
> +| `document`  | <pre>JObject</pre> | Document that cause the error                                       |
```suggestion
| `document`  | <pre>JObject</pre> | Failed replacement                                      |
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-update/index.md
> +Each updated document is an object of the `successes` array with the following properties:
```suggestion
Successful document updates are returned in the `successes` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-update/index.md
> +Each errored document is an object of the `errors` array with the following properties:
```suggestion
Failed updated are returned in the `errors` array as objects with the following properties:
```

2019-11-26 10:39 UTC, scottinet commented on doc/2/controllers/document/m-update/index.md
> +| `document`  | <pre>JObject</pre> | Document that cause the error                                       |
```suggestion
| `document`  | <pre>JObject</pre> | Failed update                                      |
```

2019-11-26 13:14 UTC, Shiranuit approved these changes

2019-11-27 11:09 UTC, scottinet approved these changes

2019-11-27 13:12 UTC, merged