Add core classes documentation
kuzzleio/sdk-csharp pull request #44
Opened 2019-11-26 09:04 UTC by Aschen

## What does this PR do ?

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

2019-11-28 10:22 UTC, y-abs requested changes

2019-11-28 10:22 UTC, Yoann-Abbes commented on doc/2/core-classes/kuzzle/constructor/index.md
> +Each instance represent a different connection to a Kuzzle server with specific options.
```suggestion
Each instance represents a different connection to a Kuzzle server with specific options.
```

2019-11-28 10:22 UTC, Yoann-Abbes commented on doc/2/core-classes/kuzzle/constructor/index.md
> +| `minTokenDuration` | <pre>int</pre> | Minimum duration of a Token before being automaticaly refreshed (If set to -1 the SDK does not refresh the token automaticaly) | yes |
```suggestion
| `minTokenDuration` | <pre>int</pre> | Minimum duration of a Token before being automatically refreshed (If set to -1 the SDK does not refresh the token automatically) | yes |
```

2019-11-28 13:53 UTC, y-abs requested changes

2019-11-28 13:53 UTC, Yoann-Abbes commented on doc/2/essentials/events/index.md
> +Occur when the SDK sends a request and the current token has expired.
```suggestion
Occurs when the SDK sends a request and the current token has expired.
```

2019-11-28 13:53 UTC, Yoann-Abbes commented on doc/2/essentials/events/index.md
> +| `user` | <pre>UserLoggedInEvent</pre>  | Contain the `kuid` of the logged in user     |
```suggestion
| `user` | <pre>UserLoggedInEvent</pre>  | Contains the `kuid` of the logged in user     |
```

2020-01-02 16:06 UTC, alexandrebouthinon approved these changes

2020-01-02 17:30 UTC, merged