Setup GH Actions
kuzzleio/sdk-csharp pull request #75
Opened 2021-06-11 08:18 UTC by xbill82

Introduce GH Actions, using the new cross-repo doc deploy system.

2021-06-14 11:52 UTC, alexandrebouthinon commented
Why not just merge 2-dev into master? By duplicating the changes in two different commits, it may lead to conflicts in a future release 😅

2021-06-15 14:22 UTC, xbill82 commented
@alexandrebouthinon bc `2-dev` has other differences from `master` and we are not releasing yet (or, at least, setting up a CI shouldn't imply a release). Plus, the files are exactly the same, this commit shouldn't introduce any conflicts.

2021-06-17 12:56 UTC, alexandrebouthinon requested changes

2021-06-17 12:56 UTC, alexandrebouthinon commented on .github/workflows/pull_request.workflow.yml
> +    name: Snippet Tests - .NET v${{ matrix.dotnet }}
```suggestion
    name: Snippet Tests
```

2021-06-17 12:56 UTC, alexandrebouthinon commented on .github/workflows/push_dev.workflow.yml
> +    name: Snippet Tests - .NET v${{ matrix.dotnet }}
```suggestion
    name: Snippet Tests
```

2021-06-17 12:56 UTC, alexandrebouthinon commented on .github/workflows/push_master.workflow.yml
> +    needs: [dead-links, deploy-prod]
Dead link check should be run before NuGet deployment

2021-08-10 09:13 UTC, xbill82 commented
Closing as feature is provided in #70, which will be merged to `master`

2021-08-10 09:13 UTC, closed without merging