Add new auth:checkRights action
kuzzleio/sdk-csharp pull request #76
Opened 2021-08-05 16:27 UTC by alexandrebouthinon

## What does this PR do ?
Close #71 
- [x] Add the new `auth:checkRights` Kuzzle API action to the supported AuthController methods
- [] Add the new `security:checkRights` Kuzzle API action to the supported SecurityController methods

### How should this be manually tested?

You could check the documentation functional tests or create your own testing C# progam using this boilerplate:
```cs
#r "Kuzzle.dll"
using System;
using System.Threading;
using System.Threading.Tasks;
using KuzzleSdk;
using KuzzleSdk.Exceptions;
using KuzzleSdk.Protocol;
using static KuzzleSdk.API.Controllers.RealtimeController;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using KuzzleSdk.Exceptions;
using KuzzleSdk.API.Options;
using KuzzleSdk.API.DataObjects;
using KuzzleSdk.API;

WebSocket socket = new WebSocket(new Uri("ws://kuzzle:7512"));
KuzzleSdk.Kuzzle kuzzle = new KuzzleSdk.Kuzzle(socket);

kuzzle.ConnectAsync(CancellationToken.None).Wait()

try {
  JObject response = await kuzzle.Auth.LoginAsync(
    "local",
    JObject.Parse("{username: 'foo', password: 'bar'}"));

  JObject requestPayload = new JObject {
    { "controller", "server"},
    { "action", "info" }
  };

  JObject res = await kuzzle.Auth.CheckRightsAsync(requestPayload);

  Console.WriteLine(res.ToString(Formatting.None));
  /*
  {
    "allowed": true,
  }
  */
} catch (KuzzleException e) {
  Console.WriteLine(e);
}
```

Do not hesitate to play with the `requestPayload` value to test several API actions

2021-08-06 12:12 UTC, Shiranuit requested changes

2021-08-06 12:12 UTC, Shiranuit commented on doc/2/controllers/auth/check-rights/index.md
> +| `allowed` | <pre>bool</pre> | a boolean telling whether the provided request would have been allowed or not |
```suggestion
A boolean telling whether the provided request would have been allowed or not
```

2021-08-06 13:20 UTC, Shiranuit approved these changes

2021-10-25 09:09 UTC, rolljee approved these changes

2022-01-10 15:16 UTC, alexandrebouthinon commented
It's not a priority

2022-01-10 15:16 UTC, closed without merging